[package]
name = "remote_invoke"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Common
anyhow = "^1.0"
tokio = { version = "^1.34", features = ["rt", "rt-multi-thread", "macros"] }
# Network
reqwest = "~0.11"
json = "~0.12"
